### ISSUE TITLE
orion should be an option for --brokerType

### ISSUE THREAD

**Issue by fgalan** [lets-fiware/ngsi-go#122]
Testing with ngsi-go version 0.8.0 if I run:

```
ngsi broker add --help
```

I see:

```
   --brokerType value              orion-ld, scorpio, stellio
```

Should "orion" been added to this list? Note that orion and orion-ld are not the same piece of software...

**Comment by fisuda** [comment]
The `--brokerType` option is for NGSI-LD brokers. (I'll add this to the documentation)
In the case of Orion, it is not needed. You can add an Orion broker (NGSIv2) with the following command. 

```
ngsi broker add --host orion --brokerHost http://localhost:1026/ --ngsiType v2
```

**Comment by fgalan** [comment]
Thanks for the feedback!

I agree it would a good idea to specify that `--brokerType` refers only to NGSI-LD brokers and it is not needed for NGSIv2.

**Comment by fgalan** [comment]
PR https://github.com/lets-fiware/ngsi-go/pull/124 solves this issue so I'm closing it.
