### ISSUE TITLE
Does ngsi-go support Keystone as IDM?

### ISSUE THREAD

**Issue by fgalan** [lets-fiware/ngsi-go#123]
I have been testing ngsi-go version 0.8.0 (very nice work by the way! :) and I have one doubt, please. Not sure if GitHub issues are the best place for doubt: if there is a better channel for this just let me know and I will use it.

Looking to "Supported FIWARE Open APIs" in the master README.md I see ngsi-go supports Keyrock API. I understand this means this security stack:

* [Keyrock](https://github.com/ging/fiware-idm) (as IDM)
* [Authzforce](https://github.com/authzforce/fiware) (as Access Control)
* [Wilma](https://github.com/ging/fiware-pep-proxy) (as PEP)

However, Orion can be used with other security stacks, which are similar but not exactly the same. In particular, we use:

* [Keystone](https://docs.openstack.org/keystone/latest) (as IDM)
* [Keypass](https://github.com/telefonicaid/fiware-keypass) (as Access Control)
* [Steelskin](https://github.com/telefonicaid/fiware-pep-steelskin) (as PEP)

What I wonder if it ngsi-go would also work in this case. As far as I know, Keystone and Keyrock are pretty similar (Keystone is the standard IDM in OpenStack, while Keyrock is a kind of derivate but supporting similar APIs... although I could be wrong).

Keystone token management operations (i.e. to get a token to be used later in a request to Orion through PEP) are based in the `POST /v3/auth/tokens` operation (more detail [here](https://docs.openstack.org/api-ref/identity/v3/?expanded=password-authentication-with-unscoped-authorization-detail#authentication-and-token-management)). I can provide more detail (a sequence of specific requests used to get a token to be used with Orion) if you need it.

Thanks!

**Comment by mapedraza** [comment]
I would like also to add that we are working together with @jason-fox for providing a tutorial using Telefonica's Security Stack, and also to include them as GEs in the catalog.

**Comment by fisuda** [comment]
@fgalan Thank you so much for testing ngsi-go!!

The NGSI Go is still under development. Therefore, it is no problem to use the GitHub issues as a channel.

The NGSI Go does not support Keystone yet. I will investigate Keystone and support it in NGSI Go.

**Comment by fisuda** [comment]
@mapedraza Thank you so much for testing ngsi-go!!

Of course, I will support Keystone for Telefonica's Security Stack in NGSI Go.

**Comment by fgalan** [comment]
> The NGSI Go does not support Keystone yet. I will investigate Keystone and support it in NGSI Go.

Don't hesitate to contact me (through this issue) if you need Keystone API utilization examples in Orion related use cases.

**Comment by fisuda** [comment]
(I have made a mistake in operating my smartphone and closed this issue. so I reopen it)

Would you give me an example of `docker-compose.yml` that is integrated orion, Keystone and Steelskin,  please?

Thank you in advance for your help

**Comment by jason-fox** [comment]
https://github.com/mapedraza/telefonica.security-stack

**Comment by fisuda** [comment]
@jason-fox  Thank you!

**Comment by fisuda** [comment]
I have created PR #126 to support Thinking Cities authentication API.
You can get a NGSI go binary from `https://repo.lab.letsfiware.jp/ngsi-go/ngsi-v0.8.0-next-linux-amd64-20210418.tar.gz`.
It would be great if you could test it and give me your feedback.

```
$ curl -O https://repo.lab.letsfiware.jp/ngsi-go/ngsi-v0.8.0-next-linux-amd64-20210418.tar.gz

$ ls -l ngsi-v0.8.0-next-linux-amd64-20210418.tar.gz
-rw-r--r-- 1 fisuda fisuda 3273531 Apr 18 06:59 ngsi-v0.8.0-next-linux-amd64-20210418.tar.gz

$ sha256sum ngsi-v0.8.0-next-linux-amd64-20210418.tar.gz
4237842f0547c0bf9a91c4b1d7101f3bf0b0350aaa5b9ca042ff22e3c2c0a315  ngsi-v0.8.0-next-linux-amd64-20210418.tar.gz

$ tar zxf ngsi-v0.8.0-next-linux-amd64-20210418.tar.gz

$ ./ngsi --version
ngsi version 0.8.0-next (git_hash:4f295fe5ada6bd5fe1496689929b9fe579154db6)

$ sudo mv ngsi /usr/local/bin

$ ngsi broker add \
  --host myinstance \
  --ngsiType v2 \
  --brokerHost http://localhost:1026 \
  --idmType ThinkingCities \
  --idmHost http://localhost:5001/v3/auth/tokens \
  --username usertest \
  --password 'ch4ng3!me' \
  --service smartcity
```

**Comment by fgalan** [comment]
I'll do a test as soon as I can and report the result here. Thanks!

**Comment by fgalan** [comment]
I have done a first test. Having a CB started in localhost as:

```
contextBroker -fg -noCache -multiservice -logLevel INFO
```

And an Keystone IDM up and running at http://idmhost:5001 with the following pre-provision:

* service: alcobendas
* service alcobendas admin: admin_alcobendas

Then I create the CB with:

```
$ ngsi broker add \
  --host myinstance \
  --ngsiType v2 \
  --brokerHost http://localhost:1026 \
  --idmType ThinkingCities \
  --idmHost http://idmhost:5001/v3/auth/tokens \
  --username admin_alcobendas \
  --password <offuscaged> \
  --service alcobendas
```

then

```
ngsi create entity --data '{"id":"E", "type": "T", "A": {"value": 1, "type": "Number"}}'
```

what the CB gets is the following (which is OK):

```
time=2021-04-19T15:30:55.657Z | lvl=INFO | corr=3b7d0288-a124-11eb-a6d1-000c29df7912 | trans=1618846128-719-00000000002 | from=0.0.0.0 | srv=alcobendas | subsrv=/ | comp=Orion | op=logTracing.cpp[130]:logInfoRequestWithPayload | msg=Request received: POST /v2/entities, request payload (60 bytes): {"id":"E", "type": "T", "A": {"value": 1, "type": "Number"}}, response code: 201
```

Next, I stop contextBroker, and run `nc -l -p 1026`. Then, I run again:

```
ngsi create entity --data '{"id":"E", "type": "T", "A": {"value": 1, "type": "Number"}}'
```

And get in the nc terminal  (which is OK):

```
POST /v2/entities HTTP/1.1
Host: localhost:1026
User-Agent: Go-http-client/1.1
Content-Length: 60
Accept: */*
Content-Type: application/json
Fiware-Service: alcobendas
Fiware-Servicepath: /
X-Auth-Token: gAAAAABgfaGkRkYv3SS4YM1oNEI80H0V5BHXHLypbD5NV4NK2JDkyQMm73X69rkVDwNPr8BTpCzzImIUv3rsBRh8DJ-dnFWlnaIdhCuOp2KNhSDeUfg_TWuoSuZJgeqocImSWtVXkGga5ApsLpi-jzqWH0zueKdL76FcGDn6BIhauikttlXijxs
Accept-Encoding: gzip
```

If I repeat this test some minutes after the first test, the X-Auth-Token is the same (which is also expected behaviour, so OK).

Thus, based on these tests I think the integration works as expected, although I have a suggestion of improvement and a doubt :)

* As far as I see, `Fiware-Servicepath: /` is always used. This is a good default, but it would be great if you could add a `--servicePath` parameter in the `ngsi broker add` operation to specify it.
* Token has an expiration period (which depends on IDM configuration but that it is in the order or hours). I understand that the current behaviour is to get the token first time CB is accessed and reuse it for a while in the next CB operations. Is NGSI-GO able to renew the token when it expires? Could you provide more detail on how this works, please?

**Comment by fisuda** [comment]
> * As far as I see, `Fiware-Servicepath: /` is always used. This is a good default, but it would be great if you could add a `--servicePath` parameter in the `ngsi broker add` operation to specify it.

You can add a service path with `--path` option in the `ngsi broker add` operation.

```
ngsi broker add \
  --host myinstance \
  --ngsiType v2 \
  --brokerHost http://localhost:1026 \
  --idmType ThinkingCities \
  --idmHost http://localhost:5001/v3/auth/tokens \
  --username usertest \
  --password '<ofuscated>' \
  --service alcobendas \
  --path /smartlight

ngsi create --host myinstance entity --data '{"id": "E"}' --keyValues
```

Or, you can add (or overwrite) a service path when you run the CRUD command.

```
ngsi broker add \
  --host myinstance \
  --ngsiType v2 \
  --brokerHost http://localhost:1026 \
  --idmType ThinkingCities \
  --idmHost http://localhost:5001/v3/auth/tokens \
  --username usertest \
  --password '<ofuscated>' \
  --service alcobendas

ngsi create --host myinstance --path /smartlight entity --data '{"id": "E"}' --keyValues

ngsi create --host myinstance --path /smartparking entity --data '{"id": "E"}' --keyValues
```

As you notice, `/` is used when specifying no service path in the case of the Thiking Cities platform.
(In the case of other IDMs, NGSI Go does nothing.)

**Comment by fisuda** [comment]
> * Tokens have an expiration period (which depends on IDM configuration but that it is in the order or hours). I understand that the current behavior in NGSI-GO is to get the token first time CB is accessed and reuse the same token for a while in the next CB operations. Is NGSI-GO able to renew the token when it expires? Could you provide more detail on how this works, please?

A token is stored in `~/.config/fiware/ngsi-go-token-cache.json` file and reused. And it is renewed just before it expires. You don't have to care about an expiration period.

You can get the remaining seconds of an expiration period using `token` command with `--expires`

```
ngsi token --host myinstance --expires
10788
```

However, in the current implementation, NGSI Go renews a token using a user and a password without using a refresh token or a token that was gotten first time. I have to improve a token renew process.

**Comment by fgalan** [comment]
Thank you for your answers! I have done a new round of tests:

Starting without any broker defined I have added two ones, one per subservice:

```
ngsi broker add \
  --host orion-alumbrado \
  --ngsiType v2 \
  --brokerHost http://localhost:1026 \
  --idmType ThinkingCities \
  --idmHost http://localhost:5001/v3/auth/tokens \
  --username admin_alcobendas \
  --password **** \
  --service alcobendas \
  --path /alumbrado

ngsi broker add \
  --host orion-residuos \
  --ngsiType v2 \
  --brokerHost http://localhost:1026 \
  --idmType ThinkingCities \
  --idmHost http://localhost:5001/v3/auth/tokens \
  --username admin_alcobendas \
  --password **** \
  --service alcobendas \
  --path /residuos
```

Now I test , with

```
ngsi create --host orion-alumbrado entity --data '{"id":"E", "type": "T", "A": {"value": 1, "type": "Number"}}'
```

and I get in the CB:

```
time=2021-04-20T16:38:55.059Z | lvl=INFO | corr=e57983e2-a1f6-11eb-bcac-000c29df7912 | trans=1618930953-639-00000000001 | from=0.0.0.0 | srv=alcobendas | subsrv=/alumbrado | comp=Orion | op=logTracing.cpp[130]:logInfoRequestWithPayload | msg=Request received: POST /v2/entities, request payload (60 bytes): {"id":"E", "type": "T", "A": {"value": 1, "type": "Number"}}, response code: 201
```

Thus, srv= and subsrv= are as expected (OK).

Now I test with

```
ngsi create --host orion-residuos entity --data '{"id":"E", "type": "T", "A": {"value": 1, "type": "Number"}}'
```

and I get in the CB:

```
time=2021-04-20T16:59:46.008Z | lvl=INFO | corr=cf1d1750-a1f9-11eb-8ebd-000c29df7912 | trans=1618930953-639-00000000002 | from=0.0.0.0 | srv=alcobendas | subsrv=/residuos | comp=Orion | op=logTracing.cpp[130]:logInfoRequestWithPayload | msg=Request received: POST /v2/entities, request payload (60 bytes): {"id":"E", "type": "T", "A": {"value": 1, "type": "Number"}}, response code: 201
```

Again, srv= and subsrv= are as expected (OK).

From my point of view, this fully validates the implementation and the PR implementing this can be merged.

**Comment by fgalan** [comment]
> A token is stored in `~/.config/fiware/ngsi-go-token-cache.json` file and reused. And it is renewed just before it expires. You don't have to take care of an expiration period.

That's exactly what I have in mind as desired behaviour :)
 
> However, in the current implementation, NGSI Go renews a token using a user and a password without using a refresh token or a token that was gotten first time. I have to improve a token renew process.

From a functional point of view, I think both ways achieve the same result. Maybe @AlvaroVega (who knows Keyrock IDM much better than me :) could provide feedback about which one should be used.

**Comment by fgalan** [comment]
I can contribute with a small tutorial document based on [my tests](https://github.com/lets-fiware/ngsi-go/issues/123#issuecomment-823446970).

If you think is a good idea and guide me a bit (in which directory create the document, file/style conventions, etc.) and can do the pull request with such contribution.

**Comment by fisuda** [comment]
> From my point of view, this fully validates the implementation and the PR implementing this can be merged.

Thank you for taking your precious time for testing it.

I will merge the PR #126.

**Comment by fisuda** [comment]
> I can contribute with a small tutorial document based on [my tests](https://github.com/lets-fiware/ngsi-go/issues/123#issuecomment-823446970).
> 
> If you think is a good idea and guide me a bit (in which directory create the document, file/style conventions, etc.) and can do the pull request with such contribution.

Thank you for the proposal.

Contributions are welcome. Could you create a tutorial document as `.md` file in `docs/tutorial` and update `mkdocs.yml` file in root, please?

**Comment by AlvaroVega** [comment]
> From a functional point of view, I think both ways achieve the same result. Maybe @AlvaroVega (who knows Keyrock IDM much better than me :) could provide feedback about which one should be used.

You should retrieve a new token using user/pass instead of using previous token in order to get a new token with full expiration time reset, otherwise you will retrieve a new token which will expires at the same time that previous token.

**Comment by fisuda** [comment]
> You should retrieve a new token using user/pass instead of using previous token in order to get a new token with full expiration time reset, otherwise you will retrieve a new token which will expires at the same time that previous token.

Thank you for your advice.

I understood that the process to get a token for keystone is fine with the current implementation.

**Comment by fisuda** [comment]
Merged #126

Thank you for your interest in NGSI Go. If you think NGSI Go is the recommended tool for FIWARE developers, I would appreciate it if you could provide a Github Star to this repository.  😄

**Comment by fgalan** [comment]
>  I would appreciate it if you could provide a Github Star to this repository. 😄

Done!

**Comment by fisuda** [comment]
Thank you! I am honored to receive a Github Star from you, the development leader of FIWARE Orion.

**Comment by fgalan** [comment]
> 
> 
> > I can contribute with a small tutorial document based on [my tests](https://github.com/lets-fiware/ngsi-go/issues/123#issuecomment-823446970).
> > If you think is a good idea and guide me a bit (in which directory create the document, file/style conventions, etc.) and can do the pull request with such contribution.
> 
> Thank you for the proposal.
> 
> Contributions are welcome. Could you create a tutorial document as `.md` file in `docs/tutorial` and update `mkdocs.yml` file in root, please?

Done in PR https://github.com/lets-fiware/ngsi-go/pull/130

**Comment by fisuda** [comment]
Merged #130.
I have created PR to solve #129. Please review it. 
I will release NGSI Go 0.8.1 after #129 is merged.

**Comment by fgalan** [comment]
I think nothing is pending on this issue :) so I'm closing it.

Thanks for the enhancements in NGSI Go!

**Comment by fisuda** [comment]
NGSI Go 0.8.1 has been released. Please see https://github.com/lets-fiware/ngsi-go/releases/tag/v0.8.1.
