### ISSUE TITLE
required host not found error at entity creatiton time but --host parameter is not recognized

### ISSUE THREAD

**Issue by fgalan** [lets-fiware/ngsi-go#127]
(I have hit this while doing the tests described in https://github.com/lets-fiware/ngsi-go/issues/123#issuecomment-822582266 but I think is bette to use it a separate issue for the report).

With the following broker configuration:

```
$ ngsi broker list
myinstance

$ ngsi broker get --host myinstance
brokerHost http://localhost:1026
ngsiType v2
FIWARE-Service alcobendas
IdmType thinkingcities
IdmHost http://iomhost:5001/v3/auth/tokens
Username admin_alcobendas
Password <offuscated>
```

If I do:

```
$ ngsi create entity --data '{"id":"E", "type": "T", "A": {"value": 1, "type": "Number"}}'
```

I get:

```
entityCreate001 required host not found
```

However, `--host` doesn't seem to be a valid option here. It doesn't appear at `ngsi create entity --help` and if I try to use it any way with:

```
ngsi create entity --data '{"id":"E", "type": "T", "A": {"value": 1, "type": "Number"}}' --host myinstance
```

I get:

```
Incorrect Usage: flag provided but not defined: -host
```

Probably I'm doing something wrong, but I don't know what...

**Comment by fisuda** [comment]
Please put `--host myinstance` between `create` and `entity` as shown:

```
ngsi create --host myinstance entity --data '{"id":"E", "type": "T", "A": {"value": 1, "type": "Number"}}'
```

The syntax of `create` command is below:

ngsi create [[common options](https://github.com/lets-fiware/ngsi-go/blob/main/docs/ngsi/create.md#common-options)] entity [[options](https://github.com/lets-fiware/ngsi-go/blob/main/docs/ngsi/create.md#options)]

Once you access a broker with/without FIWARE Serivce and/or FIWARE Path, you can omit to specify the broker next time when you run a command. Because NGSI Go stores a specified host, FIWARE Service and FIWARE SrvicePath as previous args in a config file. NGSI Go uses the previous agrs when is specified no host. The config file is `~/.config/fiware/ngsi-go-config.json`.

```
ngsi create --host orion1 entity --data '{"id":"E1"}' --keyValues

ngsi create entity --data '{"id":"E2"}' --keyValues
(Implicitly NGSI Go uses orion1 as a host.)

ngsi create --host orion2 entity --data '{"id":"E1"}' --keyValues

ngsi create entity --data '{"id":"E2"}' --keyValues
(Implicitly NGSI Go uses orion2 as a host.)
```

You can get current previous args with `ngsi settings list` as shown:

```
$ ngsi settings list
Host: myinstance
FIWARE-Service: smartcity
FIWARE-ServicePath: /
```

If you get confused about a behavior of NGSI Go, please run `ngsi settings list` command to check previous values. You can clear previous values with `ngsi settings clear`.

When multiple NGSI Go are run at the same time, there is a conflict in writing to the config file. E.g. you run NGSI Go on an interactive shell and run one in background as a batch process at same time. As a result, you may access an unexpected host.

The previous agrs are not stored in the config file when you run NGSI Go with `-B` (`--batch`) option. I recommend to use `-B`option and specify explicitly a host, FIWARE Service and FIWARE ServicePath when NGSI Go is used in a shell script.

```
#!/bin/sh
NGSIGO='ngsi -B'

${NGSIGO} create --host myinstance entity --data '{"id":"E", "type": "T", "A": {"value": 1, "type": "Number"}}'
```

Or, you can use `--config` option to use another config file.

```
#!/bin/sh
NGSIGO='ngsi --config myconfig.json'

${NGSIGO} broker add --host myinstance --ngsiType v2 --brokerHost http://localhost:1026

${NGSIGO} create --host myinstance entity --data '{"id":"E", "type": "T", "A": {"value": 1, "type": "Number"}}'
```

**Comment by fgalan** [comment]
Thank you for your detailed feedback!

Maybe what has caused my confusion is the help text:

```
$ ngsi create --help
NAME:
   ngsi create - create entity(ies), subscription or registration

USAGE:
   ngsi create command [command options] [arguments...]

COMMANDS:
   entities      create entities
   entity        create entity
   entity       create temporal entity
   subscription  create subscription
   registration  create registration
   help, h       Shows a list of commands or help for one command

OPTIONS:
   --host value, -h value     host or alias
   --token value              oauth token
   --service value, -s value  FIWARE Service
   --path value, -p value     FIWARE ServicePath
   --help                     show help (default: false)
   --version, -v              print the version (default: false)
```

Reading that, my interpretation of

```
   ngsi create command [command options] [arguments...]
```

was that after `create` token you have to put one of the commands described in the COMMANDS section (e.g. `entity`) and that in `[command options]` you use the options described in `OPTIONS` (such as `--host`).

Maybe the text for USAGE should be

```
   ngsi create [common options] command [command options] [argument...]
```

?

In addition maybe plain OPTIONS should be avoided in help messages and use things like COMMON OPTIONS and COMMAND OPTIONS to exactly match the same tokens used under USAGE (i.e. `[common option]` and `[command options]`)

**Comment by fisuda** [comment]
Thank you for the feedback. I understand.

NGSI Go uses a third-party library called `urfave/cli` to parse command line args. The library generates the help text. I will investigate it to improve the help text.

**Comment by fisuda** [comment]
The NGSI Go 0.10.0 has been released. The feature to parse command line arguments and one to print help messages has been improved. To achieve this, I had to remove third-party packages and develop alternative features that didn't rely on them. This took a long time to implement.

If you have time,  it would be great you could check if this issue has been resolved. You can get new NGSI Go binaries from the following URL:

https://github.com/lets-fiware/ngsi-go/releases/tag/v0.10.0

```
curl -OL https://github.com/lets-fiware/ngsi-go/releases/download/v0.10.0/ngsi-v0.10.0-linux-amd64.tar.gz
sudo tar zxvf ngsi-v0.10.0-linux-amd64.tar.gz -C /usr/local/bin
```

- NGSI Go version

```
$ ngsi --version
ngsi version 0.10.0 (git_hash:8385af6dff05e842ef3786a231a4bdfe0880b4bf)
```

- Print help message

```
$ ngsi create entity --help
NAME:
   ngsi create entity - create entity

USAGE:
   ngsi [global options] create entity [options] [arguments...]

CATEGORY:
   NGSI

OPTIONS:
   --host VALUE, -h VALUE     broker or server host VALUE (required)
   --service VALUE, -s VALUE  FIWARE Service VALUE
   --path VALUE, -p VALUE     FIWARE ServicePath VALUE
   --data VALUE, -d VALUE     entity data (required)
   --keyValues, -K            keyValues (default: false)
   --upsert                   upsert (default: false)
   --link VALUE, -L VALUE     @context VALUE (LD)
   --context VLAUE, -C VLAUE  @context VLAUE (LD)
   --safeString VALUE         use safe string (VALUE: on/off)
   --help                     show help (default: true)

GLOBAL OPTIONS:
   --syslog LEVEL        syslog logging LEVEL (off, err, info, debug)
   --stderr LEVEL        stderr logging LEVEL (err, info, debug)
   --configDir DIR       configuration DIR name
   --config FILE         configuration FILE name
   --cache FILE          cache FILE name
   --batch, -B           don't use previous args (batch) (default: false)
   --insecureSkipVerify  TLS/SSL skip certificate verification (default: false)

PREVIOUS ARGS:
   None
```

- Parse command line arguments

```
$ ngsi broker add --host myinstance --ngsiType v2 --brokerHost http://localhost:1026

$ ngsi broker get --host myinstance
brokerHost http://localhost:1026
ngsiType v2

$ ngsi settings list
Host: myinstance

$ ngsi settings clear

$ ngsi create entity --data '{"id":"E", "type": "T", "A": {"value": 1, "type": "Number"}}'
required002 --host not found
Run001 missing required options
```

```
$ ngsi create entity --data '{"id":"E", "type": "T", "A": {"value": 1, "type": "Number"}}' --host myinstance
```

The `--host` flag can be specified at any position of arguments. The `required host not found` error does not occur.
The same is true of other flags.

```
$ ngsi list entities --pretty
[
  {
    "id": "E",
    "type": "T",
    "A": {
      "type": "Number",
      "value": 1,
      "metadata": {}
    }
  }
]
```

**Comment by fgalan** [comment]
I have installed NGSI Go 0.10.0 and walked through your example. I can reproduce exactly the same behaviour. Now the help message is much clearer :). Thanks!

Thus, I think the issue is closed and it will be closed.

**Comment by fisuda** [comment]
Thank you for taking the time to test it!
