### ISSUE TITLE
Should use a refresh token when renewing a token.

### ISSUE THREAD

**Issue by fisuda** [lets-fiware/ngsi-go#128]
In the current implementation, when renewing a token, NGSI Go gets a token using user,.password and client_id and client_secret without using a refresh token or a token that was gotten first time.

**Comment by fgalan** [comment]
Taking into account the feedback at https://github.com/lets-fiware/ngsi-go/issues/123#issuecomment-823803861

> You should retrieve a new token using user/pass instead of using previous token in order to get a new token with full expiration time reset, otherwise you will retrieve a new token which will expires at the same time that previous token.

So maybe this issue is not needed (at least for the Keystone IDM case... I don't know if other IDMs works the same way)

**Comment by fisuda** [comment]
I understood that the process to get a token for keystone is fine with the current implementation. But, I keep this issue open for other IDMs to renew a token with a refresh token.

**Comment by fisuda** [comment]
This issue has been solved by #166. However, it does not affect the procedure for getting a token for Keystone.
