### ISSUE TITLE
Obfuscate password in ngsi broker get result (explicit showing it based on parameter)

### ISSUE THREAD

**Issue by fgalan** [lets-fiware/ngsi-go#129]
This is a small improvement suggestion.

With `ngsi broker get` you can get information like this:

```
$ ngsi broker get --host orion-alumbrado
brokerHost http://localhost:1026
ngsiType v2
FIWARE-Service alcobendas
FIWARE-ServicePath /alumbrado
IdmType thinkingcities
IdmHost http://idmhost:5001/v3/auth/tokens
Username admin_user
Password user_password
```

The problem is that when the broker setting is using an IDM (I have observed it for ThinkingCities one but I guess that for other IDM types it would be the same) the password appears in clear text.

Maybe a possible improvement would be by default ofuscating that information, i.e:

```
$ ngsi broker get --host orion-alumbrado
brokerHost http://localhost:1026
ngsiType v2
FIWARE-Service alcobendas
FIWARE-ServicePath /alumbrado
IdmType thinkingcities
IdmHost http://idmhost:5001/v3/auth/tokens
Username admin_user
Password ****
```

and require an explicit parameter to see it in clear text, i.e.:

```
$ ngsi broker get --host orion-alumbrado --cleartextPassword
brokerHost http://localhost:1026
ngsiType v2
FIWARE-Service alcobendas
FIWARE-ServicePath /alumbrado
IdmType thinkingcities
IdmHost http://idmhost:5001/v3/auth/tokens
Username admin_user
Password user_password
```

(`cleartextPassword` is just a suggestion... of course it could a better one, based on the conventions used for parameter names in NGSI Go)

Note this is not to achieve perfect security (user can use `--cleartextPassword` without any restriction and, in any case, check the information in the filesystem storage used by NGSI Go) but a equivalent feature to the one in browsers and similar systems (see picture below)

![imagen](https://user-images.githubusercontent.com/1534240/115439530-f6df4000-a20e-11eb-93ba-c814d16cb14f.png)

**Comment by fisuda** [comment]
Thank you for the feedback!

I agree with your proposal. I will create a PR to support this feature and ask you to review it.

**Comment by fgalan** [comment]
Implemented by PR https://github.com/lets-fiware/ngsi-go/pull/131. Closing.
