### ISSUE TITLE
Subscriptions with empty attrs condition are mangled on insert (Bad Request)

### ISSUE THREAD

**Issue by Siedlerchr** [lets-fiware/ngsi-go#201]
Using current master version.

I wanted to add the following: subscription using the ngis-go tool:

`ngsi create --host orion-with-apikey subscription --data @SingleSubcriptionTest `

orion is running as docker container: fiware/orion:3.2.0

Executing gives a 400  bad request. Inserting the subscription using Postman works fine.
```
0.9.0 (git_hash:bfd1ec240a8a8421929e2923f8fb5d3f6cab18ab) (git_hash:bfd1ec240a8a8421929e2923f8fb5d3f6cab18ab)
subscriptionsCreate
InitTokenMgr
subscriptionsCreateV2004 400 Bad Request {"error":"BadRequest","description":"condition is empty"}
abnormal termination
```
I switched orion to debug and this is the payload I see in the logs.
The conditions object is empty

```
| comp=Orion | op=logTracing.cpp[141]:logInfoRequestWithPayload | msg=Request received: POST /v2/subscriptions, request payload (238 bytes): {"description":"Test Notification","subject":{"entities":[{"idPattern":"Alert.*","type":"Alert"}],"condition":{}},"notification":{"httpCustom":{"url":"http://dev/null","headers":{"fiware-shared-key":"test"}},"attrsFormat":"keyValues"}}, response code: 400
```

Save the json as SingleSubcriptionTest.json 
```
{
    "description": "Test Notification",
    "subject": {
      "entities": [
        {
          "idPattern": "Alert.*",
          "type": "Alert"
        }
      ],
      "condition": {
        "attrs": []
      }
    },
    "notification": {
      "httpCustom": {
        "url": "http://dev/null",
        "headers": {
          "fiware-shared-key": "test"
        }
      },
      "attrsFormat": "keyValues"
    }
  }

```

**Comment by Siedlerchr** [comment]
Seems like I stumbled over this issue  https://github.com/golang/go/issues/31811  🙄

**Comment by fisuda** [comment]
Thank you for the feedback!

As a workaround, I added `--raw` option to the commands for creating and getting a subscription.

You can get a NGSI go binary from `https://repo.lab.letsfiware.jp/ngsi-go/ngsi-v0.9.0-next-linux-amd64-20211006.tar.gz`. It would be great if you could test it and give me your feedback.

```
curl -O https://repo.lab.letsfiware.jp/ngsi-go/ngsi-v0.9.0-next-linux-amd64-20211006.tar.gz
```
The source code is here: https://github.com/fisuda/ngsi-go/tree/issue/201-subs

```
$ cat /tmp/test.json
{
  "description": "Test Notification",
  "subject": {
    "entities": [
      {
        "idPattern": "Alert.*",
        "type": "Alert"
      }
    ],
    "condition": {
      "attrs": []
    }
  },
  "notification": {
    "httpCustom": {
      "url": "http://dev/null",
      "headers": {
        "fiware-shared-key": "test"
      }
    },
    "attrsFormat": "keyValues"
  }
}
```

```
$ ngsi create --host orion subscription --data @/tmp/test.json --raw
615d5b66f19d2a10c44e264c
```

```
$ ngsi get subscription --id 615d5b66f19d2a10c44e264c --pretty --raw
{
  "id": "615d5b66f19d2a10c44e264c",
  "description": "Test Notification",
  "status": "active",
  "subject": {
    "entities": [
      {
        "idPattern": "Alert.*",
        "type": "Alert"
      }
    ],
    "condition": {
      "attrs": []
    }
  },
  "notification": {
    "attrs": [],
    "onlyChangedAttrs": false,
    "attrsFormat": "keyValues",
    "httpCustom": {
      "url": "http://dev/null",
      "headers": {
        "fiware-shared-key": "test"
      }
    }
  }
}
```

**Comment by Siedlerchr** [comment]
Thanks for the quick response. I found another workaround,  the condition attribute is also optional and orion will create a condition with an empty attrs array.

Can you please provide a mac binary for testing? (And there seems something wrong with the branch?, I don't see your changes in that branch)

**Comment by fisuda** [comment]
I uploaded mac binaries for amd64 and arm64.

```
curl -O https://repo.lab.letsfiware.jp/ngsi-go/ngsi-v0.9.0-next-darwin-amd64-20211006.tar.gz
```

```
curl -O https://repo.lab.letsfiware.jp/ngsi-go/ngsi-v0.9.0-next-darwin-arm64-20211006.tar.gz
```

**Comment by fisuda** [comment]
The NGSI Go 0.10.0 has been released. And this issue is closed because this feature has been officially added to NGSI Go.
You can get NGSI Go binaries which you need from the following URL:
 
- https://github.com/lets-fiware/ngsi-go/releases/tag/v0.10.0

Thanks!
