### ISSUE TITLE
uppercase fiware-service

### ISSUE THREAD

**Issue by modularTaco** [lets-fiware/ngsi-go#40]
Hey guys,

I was just checking if i could use your tool to access an orion instance, but unfortunately i'm failing already in the beginning.

It seems that you do not support fiware-services with uppercase letters (seems to be intented as you test that uppercase fiware services are producing an error):
https://github.com/lets-fiware/ngsi-go/blob/1a07b10911df686410566f299b885551fc2313fc/internal/ngsilib/validation_test.go#L27
Is there any reason for this?

The problem is, the orion instance i want to connect to uses fiware services like `Foo` instead of `foo` and if i try to connect with a lowercase fiware service, it does not work.  

Does work:
```
➜ ngsi broker add \
  --host myinstance \
  --brokerHost http://localhost:1026 \
  --ngsiType v2 \
  --service foo \
  --path /iot
```

Does not work
```
➜ ngsi broker add \
  --host myinstance \
  --brokerHost http://localhost:1026 \
  --ngsiType v2 \
  --service Foo \
  --path /iot
```

With this error: `brokersAdd007 error FIWARE Service: Foo`

**Comment by fisuda** [comment]
Orion interprets the tenant name (fiware-service name) in lowercase. To use a coherent tenant name, NGSI Go allows only lowercase letters in tenant names.

Please have a look at `MULTI TENANCY` section in Orion documentation.

https://fiware-orion.readthedocs.io/en/master/user/multitenancy/index.html

> Orion Context Broker interprets the tenant name in lowercase, thus, although you can use tenants such as in updateContext "MyService" it is not advisable, as the notifications related with that tenant will be sent with "myservice" and, in that sense, it is not coherent the tenant you used in updateContext compared with the one that Orion sends in notifyContextRequest.

**Comment by modularTaco** [comment]
Thanks for the clarification!
